# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bed459a8-9cf9-4d57-a201-73139a427094";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."luks-71194e75-bc13-473d-a582-52b17f47acb5".device = "/dev/disk/by-uuid/71194e75-bc13-473d-a582-52b17f47acb5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5592-C106";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/myexternaldisk" =
    { device = "/dev/disk/by-uuid/2ADB59CE560FF235";
      fsType = "ntfs";
      options = [ 
        "rw"
        "nosuid"
        "nodev"
        "relatime"
        "user_id=0"
        "group_id=0"
        "allow_other"
        "blksize=4096"
        "x-gvfs-show"
      ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
